FROM alpine:3.5

RUN \
  apk add --update git go make gcc musl-dev linux-headers ca-certificates openssl bash && \
  update-ca-certificates                                                               && \
  git clone https://github.com/ethereum/go-ethereum                                    && \
  (cd go-ethereum && make geth)                                                        && \
  cp go-ethereum/build/bin/geth /geth                                                  && \
  apk del git go make gcc musl-dev linux-headers                                       && \
  rm -rf /go-ethereum && rm -rf /var/cache/apk/*

RUN \
  wget https://raw.githubusercontent.com/MaximilianMeister/kubernet-eth/master/scripts/start_miner_dev.sh -O /start_miner_dev.sh && \
  chmod +x /start_miner_dev.sh

EXPOSE 8545
EXPOSE 30303

ENTRYPOINT ["/start_miner_dev.sh"]
